language: go

go:
  - 1.7

sudo: false

env:
  matrix:
  - RACK_OS=linux RACK_ARCH=amd64
  - RACK_OS=darwin RACK_ARCH=amd64
  - RACK_OS=windows RACK_ARCH=amd64
  - RACK_OS=linux RACK_ARCH=arm GOARM=6
  - RACK_OS=linux RACK_ARCH=arm GOARM=7

before_install:
  - go version
  - go env

install:
- go get -d -v ./...

script:
  - if [[ $RACK_OS == "linux" && $RACK_ARCH == "amd64" ]]; then GOARCH=$RACK_ARCH GOOS=$RACK_OS go test github.com/rackspace/rack/commands/... -v; fi

before_deploy:
- "./script/prep-travis-release.sh"
- cd build

deploy:
  provider: cloudfiles
  username: rackcli.drgsites
  region: IAD
  api-key:
    secure: B94hK9XBKfav8TdEPIhjwWTEKGXmcJzmZhnYDzN6YOEbfgq9ZhNfYQzHzKrcoZQUG8/mLjQUjUBxJPPlccw4UOilf7Fe0NKzI9bNxjUTwlmfGXMjOvT1CrAF/mzgr35wsGHB8N6JQwGepdhCdMC2SmywZid13DQDmm1B3c7dUNg=
  container: rackclibuilds
  skip_cleanup: true
  on:
    all_branches: true

notifications:
  slack:
    secure: GGxapXtJ6ijPWdFdIypPwuz9nDvKbj1cmLf0edmRBDNTLbg2a1RPyFugxJbd2hEqak62m5Ue3ppY+J+boJXP2n1Eb/FOQelZd3V3lxNPpvoYgJzzq+g/TlSLakposn30PG3ySOAvtvIwGbUrbVsVS3ASBzt9s39N3HoE1CufUDA=
